name: Deploy em Produção
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Conectar na VPS e fazer deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "☑ Atualizando código..."
            cd ~/live_trivia/live_trivia
            git pull origin main
            
            echo "☑ Construindo a nova imagem Docker..."
            docker build -t live-trivia .
            
            echo "☑ Parando e removendo o container antigo (se existir)..."
            docker stop live-trivia || true
            docker rm live-trivia || true
            
            echo "☑ Iniciando o novo container..."
            docker run -d --name live-trivia --restart unless-stopped -p 3070:3070 -e SECRET_KEY_BASE="yngGTAh528QFKnBWXb03YdEk0Tb6p3Z1Bfo99Ff+toyndIT6PcYy5Fvl1dNSgeyGNTYGU8PYbt+TU7newsGsBw==" -e PHX_HOST="livetrivia.frameworksweb.com.br" -e PORT=3070 -e MIX_ENV=prod live-trivia
            
            echo "☑ Limpando imagens antigas..."
            docker image prune -f
            
            echo "☑ Deploy concluído! Status do container:"
            docker ps -f name=live-trivia